# --------------------------------------------------
# Site Settings
# --------------------------------------------------

# Menu
menu:
  home: / || Home
  writing: /categories/writing/ || Writing
  books: /books/ || üìö
  archives: /archives/ || Archives
  tags: /tags/ || Tags
  about: /about/ || About

# Color
color:
  text: '#33333D'
  text-secondary: '#4e4e4e'
  text-third: '#999999'
  background: '#ffffff'
  background-secondary: '#f6f8fa'
  border: '#eeeeee'
  text-dark: '#dddddd'
  text-secondary-dark: '#9899ab'
  text-third-dark: '#7d8594'
  background-dark: '#1e2128'
  background-secondary-dark: '#1a1d22'
  border-dark: '#2b3038'
  link: '#FF3B00'
  link-gradient: 'linear-gradient(-60deg, #ff5858 0%, #f09819 100%)'

# Favicon
favicon:
  small: /images/icons/favicon-16x16.png
  medium: /images/icons/favicon-32x32.png
  apple_touch_icon: /images/icons/apple-touch-icon.png
  safari_pinned_tab: /images/icons/stun-logo.svg
  msapplication: /images/icons/favicon-144x144.png

# Font
font:
  size: 14px
  family:

# Background Image
background_image: 

# Loading
loading:
  gif: /images/theme/loading.gif

# Preview
preview:
  enable: true
  type: wave  # wave | cloud
  background:
    type: image # image video
    default_image:
      light: /pics/about/bgi-light.jpeg
      dark: /pics/about/bgi-dark.jpeg
    video:
    # api: https://source.unsplash.com/random/1920x1080
    size: cover # css: background-size
    position: center # css: background-position
  motto:
    default: HELLO_E$THER
    color: '#ffffff'
    typing: true
    api: # https://v2.jinrishici.com/one.json
    data_contents: ['data', 'content']
    # ex.one  =>  apl: https://v1.hitokoto.cn/?encode=text&c=i  data_contents:
    # ex.two  =>  api: https://v2.jinrishici.com/one.json  data_contents: ['data', 'content']

# Navbar
navbar:
  enable: true
  back_home: true

# Copyright
copyright: Copyright &copy; 2021 Esther Li

# Social
social:
  github: https://github.com/29Esther || icongithub-fill || '#9f7be1'
  email: mailto:esther_lzx@163.com || iconmail
  weibo: http://weibo.com/2249721655/profile?topnav=1&wvr=6 || iconweibo || '#9f7be1'
  # linkedin: https://www.linkedin.com/in/lizhixuan || icongithub-fill || '#9f7be1'

# Override Scrollbar
scrollbar:
  type: default # default | simple | normal | none

# Fab (Float Action Button)
fab:
  enable: false
  always_show: false

# Search
search:
  enable: true

# QR Code
qrcode:
  enable: false
  type: url # url | image

# Color Mode
color_mode:
  enable: true

# Gray (Mourning Mode)
gray:
  enable: false

# --------------------------------------------------
# Post Settings
# --------------------------------------------------

# Excerpt
excerpt: 
  enable: true

# Post Image
post_image:
  random: local # local galleries
  default: /images/theme/post-image.jpg

# Page Size
post_page_size:
  width: 800px

# Caption
caption:
  enable: true

# Indent
indent:
  content:
  excerpt:

# TOC
toc:
  enable: true
  always_show: true
  min_depth: 1
  max_depth: 3

# Donate
donate:
  enable: true
  alipay: /images/donation/alipay.png
  wechat: /images/donation/wechat.png

# Copyright
post_copyright:
  enable: true

# CarrierÔºàcopy article with one clickÔºâ
carrier:
  enable: true
  type: html # html | markdown | text

# --------------------------------------------------
# Page Settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true
  title: ÊëÑÂΩ±
  subtitle: Photography
  type: waterfall # waterfall | grid
  columns: 3


# --------------------------------------------------
# Comment Settings
# --------------------------------------------------

comments:
  enable: false
  type: valine # gitalk | valine | changyan
  button: true

# Gitalk
gitalk:
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# Valine
valine:
  appId:
  appKey:
  placeholder: ÈõÅËøáÁïôÁóï
  avatar: mp
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  conf:

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Notification
notification:
  enable: false
  delay: 4500
  page_white_list:
  page_black_list:

# Daovoice
daovoice:
  enable: false
  appId: # app_id

# Tencent Chao
tencentChao:
  enable: false
  appId: # app_id

# LeanCloud
leancloud:
  enable: false
  appId:
  appKey:
  serverURLs: https://leancloud.cn/

# Lazyload
lazyload:
  enable: true
  only_post: false
  loading:
    gif: /images/theme/loading.gif
    lottie:

# FancyBox
fancybox: true

# Pjax
pjax: false

# HighLight
highlight:
  enable: true
  style: # https://highlightjs.org/static/demo/
    light: Xcode
    dark: Solarized Dark

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu: # id
  google: # id
  tencent: # id
  cnzz: # id

# --------------------------------------------------
# Script Settings
# --------------------------------------------------

# CDN
vendors:
  jquery_js: https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js
  fancybox_js: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://cdn.bootcdn.net/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  qrcode_js: https://cdn.bootcdn.net/ajax/libs/jquery.qrcode/1.0/jquery.qrcode.min.js
  daovoice_js: https://widget.daovoice.io/widget/0f81ff2f.js
  lottie_js: https://cdn.bootcdn.net/ajax/libs/lottie-web/5.7.12/lottie.js
  fancybox_css: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://cdn.bootcss.com/highlight.js/9.18.1/styles/
  iconfont_css: //at.alicdn.com/t/font_1445822_p6ry5n7lrr.css

# Custom
custom:
  head:
  foot:
  css:
  js:
